### PR TITLE
Added get_label function to pytorch bindings (nvvl.VideoDataset)

### PR DESCRIPTION
**Pull request by Multihuntr**
Added an optional parameter to the pytorch nvvl.VideoDataset that is a callable which obtains the labels for a filename/frame.

I changed the return for `__next__` on VideoLoader to include the labels. I also updated every reference I could find to VideoLoader.__next__ in the other code (it's entirely possible I missed one; I couldn't test the other code because I don't have access to the base docker image in `//pytorch/test/docker/Dockerfile`.

I believe that labels are ubiquitous to use cases, so I think that it is acceptable that it is always returned. 

I couldn't find any uses of VideoDataset.__getitem__ in the code base.

Please advise for any changes/tests you want.

### CODE REVIEW

**Comment by Multihuntr** [comment]
#21 
Solved, hopefully!

**Comment by Multihuntr** [comment]
Unfortunately, the result is simply a parallel list to the batched frames (and `VideoLoader` doesn't implement a collate_fn), so you'll have to collate complex structures yourself.

**Comment by jaredcasper** [comment]
Sorry for the delay, this look good.  Thanks for contributing!

One small request.  What do you think about having `VideoDataset.__getitem__` and `VideoLoader.__next__` just return the tensor/tensor map instead of the tuple in the case that `get_label` is `None`?  This way any existing code shouldn't have to change as the interface remains the same unless `get_label` is defined.

**Comment by Multihuntr** [comment]
Ok, done.
And here's some manual "tests" that I did to make sure it worked: https://gist.github.com/Multihuntr/02a935a165a291f59d13ce215f41b088

**Comment by jaredcasper** [comment]
Thanks for the contribution!

Those manual tests are basically all I've ever done to test things as well (beyond actual use). An actual test suite of some sort would be good at some point... but so much to do... :)

**Comment by omg777** [comment]
@Multihuntr Thanks for the nice codes.
I want to use VideoLoader for the Object detection problem. then how can I prepare the labels of the video ?
In image field, I just make multiple bboxes informations in .txt file per image.

**Comment by Multihuntr** [comment]
My preference is to have like a json label file per video, and in the program, a label object which reads that file at the start of the program and caches the labels, and describes any label manipulation you need to do.

As it currently stands, you can use the get_label like this.

```
# create your get_label function, assuming a dictionary of label objects with .label functions
def get_label(filename, frame_num):
    return labels[filename].label(frame_num)

dataset = nvvl.VideoDataset(all_filenames, sequence_length, get_label=get_label)
# ... Carry on as normal
```


For the object detection problem, if you use random flips or random crops, then you'll need to also pass that information to your get_label function. I'm going to put another pull request in that does this. When it's in, you'll just do this

```
def get_label(filename, frame_num, transformations):
    raw_label = labels[filename].label(frame_no)
    fixed_label = labels[filename].correct_labels(raw_label, transformations)
```

But this second way isn't in yet (later this week I'll put in a pull request)

**Comment by Multihuntr** [comment]
I've put in #43 

Up to jaredcasper to merge if/when he wills.

**Comment by omg777** [comment]
@Multihuntr Thanks for your support!
I have some questions for load video.
Now I prepared video data via :
`ffmpeg -i original.mp4 -map v:0 -c:v libx264 -crf 18 -pix_fmt yuv420p -g 5 -profile:v high prepared.mp4
`
I`m wondering how to numbering frame_number with this video. Because of the FPS.
`dataset = nvvl.VideoDataset(**filenames**, sequence_length, get_label, ...`
Just put filenames here, how can this match labels and video_frames ?

**Comment by Multihuntr** [comment]
I'm not sure I follow your question. The VideoDataset gives the frame number within the video that it tells you. So if you have 100 videos, all 1000 frames long, and you ask for the 0th element you get the first frame of the first video (and when get_label is called it receives ("video1.mp4", 0)), but if you ask for the 4651 frame, then it gives you the 652nd frame of the 4th video (and get_label receives ("video4.mp4", 651)), and if you ask for frame 89195, then you get ("video89.mp4", 195)).
FPS doesn't have anything to do with it.

If you're wondering how to make your labels get associated with particular frame numbers, then that's mostly going to be up to you. It depends on what format your labels already are in. I would be shocked if your labels were associated with timestamps instead of frame numbers, but if they are, you can only use one FPS per VideoDataset, so I would hard code whatever it is and multiply by the time stamp to find the frame number.

Typically, I load all of my labels into RAM at once and have a dictionary or list per video that can be indexed by frame number.

**Pull request merged**
