### PR TITLE
Made pytorch VideoLoader's buffer_length an __init__ parameter.

### PR DESCRIPTION
**Pull request by Multihuntr**
I had a problem that the default value was using up too much memory (4K frames are big, you know). I figure this should be an init parameter.

P.S. Sorry that there's a bunch of pull requests from me. There's just stuff I need NVVL to do. Hope that's cool (i.e. let me know if I should just stop)

### CODE REVIEW

**Comment by bryancatanzaro** [comment]
Pull requests are awesome! Don't stop!

**Comment by Multihuntr** [comment]
@jaredcasper @bryancatanzaro 
*Bump*

(I kind of want this feature to be in there soon, can you accept or reject it?)

**Comment by jaredcasper** [comment]
Sorry for the delay @Multihuntr, was busy with other projects last month and am now on vacation with limited connectivity.  I will hopefully get to this next week.  I appreciate your contributions!

**Comment by Multihuntr** [comment]
I don't mean to be rude, @PeterHuang2015, but I'm not really clear why merging the different independent pull requests makes it better from a source code management perspective.

From my perspective, it should be easier to evaluate (and accept/reject) each one if they are completely independent, especially if they want one of them, but don't want another one. Although there's more clicks, there's less overall mental load on checking that it's correct before accepting them and less hassle in the case of rejecting something (or asking for changes).

**Pull request merged**
